/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
        banking: {
          dark: '#0f172a',
          card: '#1e293b',
          accent: '#6366f1',
          success: '#10b981',
          warning: '#f59e0b',
          error: '#ef4444',
          info: '#3b82f6',
        },
        // Material Design 3 tokens
        'm3': {
          'primary': '#4343d5',
          'on-primary': '#ffffff',
          'primary-container': '#5d5fef',
          'on-primary-container': '#faf7ff',
          'primary-fixed': '#e1e0ff',
          'primary-fixed-dim': '#c1c1ff',
          'on-primary-fixed': '#07006c',
          'on-primary-fixed-variant': '#2e2bc2',
          'secondary': '#565e71',
          'on-secondary': '#ffffff',
          'secondary-container': '#dbe2f9',
          'on-secondary-container': '#5c6477',
          'secondary-fixed': '#dbe2f9',
          'secondary-fixed-dim': '#bfc6dc',
          'on-secondary-fixed': '#141b2c',
          'on-secondary-fixed-variant': '#3f4759',
          'tertiary': '#5a5961',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#73717a',
          'on-tertiary-container': '#fbf7ff',
          'tertiary-fixed': '#e4e1eb',
          'tertiary-fixed-dim': '#c8c5ce',
          'on-tertiary-fixed': '#1b1b22',
          'on-tertiary-fixed-variant': '#47464e',
          'error': '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          'background': '#f9f9ff',
          'on-background': '#111c2d',
          'surface': '#f9f9ff',
          'on-surface': '#111c2d',
          'surface-variant': '#d9e3fb',
          'on-surface-variant': '#464555',
          'surface-dim': '#d0daf2',
          'surface-bright': '#f9f9ff',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#f0f3ff',
          'surface-container': '#e8eeff',
          'surface-container-high': '#dfe8ff',
          'surface-container-highest': '#d9e3fb',
          'surface-tint': '#4849da',
          'inverse-primary': '#c1c1ff',
          'inverse-surface': '#273143',
          'inverse-on-surface': '#ecf0ff',
          'outline': '#767586',
          'outline-variant': '#c7c4d7',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '30px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'gutter': '24px',
        'container-max': '1280px',
      },
      backdropBlur: {
        xs: '2px',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-in': 'slideIn 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateX(-10px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
    },
  },
  plugins: [],
}
